#Exceptions

raise Exception('An error!')
print(result)
